### PR TITLE
[DSP-1011]-Disable urlTracker on publishing in CMS

### PR DESCRIPTION
**Pull request by Azadeh-h**
@matt-sm @hiroyoneyama

### CODE REVIEW

**Comment by hiroyoneyama** [comment]
:+1:

**Comment by matt-sm** [comment]
What about moving/deleting events?

**Comment by Azadeh-h** [comment]
Good point. removed them. I didn't delete the whole file in case those clean ups have any affect on site performance

**Comment by matt-sm** [comment]
:+1:

**Pull request merged**
